package main

// 执行命令
// PS E:\Workspace\Go\example> go run ./ ..
func main() {
	// hello()
	// values()
	//variables()
	// constants()
	// testFor()
	// testIfElse()
	// testRange()
	// testArray()
	// testSlice3()
	// testMap()
	// testFunction()
	// testMultiReturn()
	// testMultiParams()
	// testClosure()
	// testRecursion()
	// testPtr()
	// testStringRune()
	// testStruct()
	// testStructFunc()
	// testInterface()
	// testError()
	// testPanic()
	// testDefer()
	// testTimer()
	// timeStamp()
	// timeFormat()
	// testStrings()
	// testGoroutine()
	// testChannels()
	// testChannelsBuffer()
	// testChanSync()
	// testOnlyRWChan()
	// testSelectChan()
	// testSelectTimeout()
	// testNonBlockingSelect()
	// testChanClose()
	// testChanRange()
	// testTicker()
	// testWorker()
	// testWaitGroup()
	// testLimiting()
	// testAtom()
	// testMutexes()
	// testStatefulGoroutines()
	// testSort()
	// testSortByFun()
	// testRecover()
	// teststrFormat()
	// testTemplate()
	// testRegular()
	// testJson()
	testReflect()
}
